blank_issues_enabled: false
contact_links:
  - name: Retail?
    url: https://github.com/DeadlyBossMods/DeadlyBossMods/issues/new/choose
    about: Is your issue for retail WoW?
  - name: Classic Era?
    url: https://github.com/DeadlyBossMods/DBM-Classic/issues/new/choose
    about: Is your issue for Classic Era WoW?
